Alter table TBLEMPLYOEE_REPORT Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBL_BANK_DOCUMENTS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBL_DOCUMENTS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLJOBS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBL_CTC_DOCUMENTS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBL_EDUCATION_DOCUMENTS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBL_PREVIOUS_COMPANY_DOCUMENTS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEE Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEE_ACADEMICSDETAILS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEE_ADDRESS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEE_CTCCOMPONENTVALUE Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEE_DECLARATION Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEE_DEPENDENTSDETAILS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEE_EXPERIENCEDETAILS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEE_GENERALINFORMATION Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEE_PREVIOUSEMPLOYERDETAILS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEE_REFERENCEDETAILS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLYOEE_CTCADDITIONALDETAILS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBL_BASIC_DOCUMENTS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBL_EMPLOYEE_MEDICLAIM_DECLARATION Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBL_GENERAL_DOCUMENTS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBL_PLEDGE_OF_ACTION Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLLOGIN Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLMASTARDATATYPE Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLMASTARDATA Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLCTCCOMPONENT Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEESTATUS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLCITYMASTER Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);
Alter table TBLEMPLOYEE_BANK_DETAILS Add ( ATTRIBUTE1 VARCHAR2(250 BYTE),ATTRIBUTE2 VARCHAR2(250 BYTE),ATTRIBUTE3 VARCHAR2(250 BYTE),ATTRIBUTE4 VARCHAR2(250 BYTE),ATTRIBUTE5 VARCHAR2(250 BYTE),ATTRIBUTE6 NUMBER,ATTRIBUTE7 NUMBER,ATTRIBUTE8 NUMBER,ATTRIBUTE9 DATE,ATTRIBUTE10 DATE);



--report column
    alter table tblemplyoee_report add "ACCOUNT_NUMBER" NVARCHAR2(200);
	alter table tblemplyoee_report add "BANK_NAME" NVARCHAR2(300);
	alter table tblemplyoee_report add "IFSC_CODE" NVARCHAR2(300);
	alter table tblemplyoee_report add "BANK_ADDRESS" NVARCHAR2(500);
    alter table tblemplyoee_report add "Monthly_Basic" NUMBER(18,5);
    alter table tblemplyoee_report add "Yearly_Basic" NUMBER(18,5);
	alter table tblemplyoee_report add "Monthly_HRA_CLA" NUMBER(18,5);
    alter table tblemplyoee_report add "Yearly_HRA_CLA" NUMBER(18,5);
	alter table tblemplyoee_report add "Monthly_Conveyance" NUMBER(18,5);
    alter table tblemplyoee_report add "Yearly_Conveyance" NUMBER(18,5);
	alter table tblemplyoee_report add "Monthly_SpecialAllowance" NUMBER(18,5); 
    alter table tblemplyoee_report add "Yearly_SpecialAllowance" NUMBER(18,5);
    alter table tblemplyoee_report add "Monthly_LTA" NUMBER(18,5);
    alter table tblemplyoee_report add "Yearly_LTA" NUMBER(18,5);
	alter table tblemplyoee_report add "Monthly_Medical" NUMBER(18,5);
    alter table tblemplyoee_report add "Yearly_Medical" NUMBER(18,5);
	alter table tblemplyoee_report add "Monthly_Bonus" NUMBER(18,5);
    alter table tblemplyoee_report add "Yearly_Bonus" NUMBER(18,5);
	alter table tblemplyoee_report add "Monthly_PF" NUMBER(18,5);
    alter table tblemplyoee_report add "Yearly_PF" NUMBER(18,5);
    alter table tblemplyoee_report add "Monthly_Gratuity" NUMBER(18,5);
    alter table tblemplyoee_report add "Yearly_Gratuity" NUMBER(18,5);
	alter table tblemplyoee_report add "Monthly_Superannuation" NUMBER(18,5);
    alter table tblemplyoee_report add "Yearly_Superannuation" NUMBER(18,5);
	alter table tblemplyoee_report add "Monthly_Others" NUMBER(18,5);
    alter table tblemplyoee_report add "Yearly_Others" NUMBER(18,5);
	alter table tblemplyoee_report add "Monthly_Total" NUMBER(18,5);
    alter table tblemplyoee_report add "Yearly_Total" NUMBER(18,5);
    alter table tblemplyoee_report add "ctcexpected" NUMBER(10,0);
    alter table tblemplyoee_report add "presentjobresponsisblities" NVARCHAR2(500);
	alter table tblemplyoee_report add "positionstructure" NVARCHAR2(100);
    alter table tblemplyoee_report add "contributioninforpastemployer" NVARCHAR2(500);
	alter table tblemplyoee_report add "membershipofprofessionalorganisation" NVARCHAR2(300);
    alter table tblemplyoee_report add "trainingprogrammeattended" NVARCHAR2(300);

    	alter table tblemplyoee_report add "employeraddress" NVARCHAR2(500);
    alter table tblemplyoee_report add "telephone" NVARCHAR2(12);
    alter table tblemplyoee_report add "fax" NVARCHAR2(12);
    alter table tblemplyoee_report add "initialdesignation" NVARCHAR2(50);
    alter table tblemplyoee_report add "reasonforchange" NVARCHAR2(500);

















	-------------------Prod deployment 1 june 2024

	 update tbl_documents set description='Offer letter, Resignation Mail and Last 3 month Salary slip' where screen='Present_Employer_Document';
    commit;
    